
INSERT INTO PARTE (PARTEID, NOME, SEXO, DOCUMENTO, TIPOPESSOA, IDENTIDADE, NASCIMENTO, FUNDACAO, TELEFONECOMERCIAL, TELEFONECELULAR, PROFISSAO, ESTADOCIVIL, EMAIL, LOGRADOURO, BAIRRO, CIDADE, ESTADO, PAIS) VALUES (4, 'CAIXA ECONOMICA FEDERAL', '0', '00.360.305/0001-04', 'Jurídica', NULL, NULL, '3-FEB-1971', '(61) 3521-8600', NULL, NULL, NULL, NULL, 'ST BANCARIO SUL QUADRA 04, 34', 'ASA SUL', 'BRASILIA', 'DF', NULL);

